### PR TITLE
Create a search based document for write-the

### PR DESCRIPTION
**Pull request by James4Ever0**
This document is generated using: https://github.com/james4ever0/prometheous

You can view the website at: https://james4ever0.github.io/write-the/

### CODE REVIEW

**Comment by Wytamma** [comment]
Hi @James4Ever0, thanks for the PR! Can you explain what it is? 😅 it looks like you can search the code but that's already available through the mkdocs website e.g.
image

**Comment by James4Ever0** [comment]
> Hi @James4Ever0, thanks for the PR! Can you explain what it is? 😅 it looks like you can search the code but that's already available through the mkdocs website e.g. image

I want to explain that this tool is language agnostic. It does not analyze the code AST and split it by functions. Instead it splits the code into chunks. I have already finished the chunk comment, summation and search functionality.

I am currently working on file hierarchy functionality so people can see summaries of folders and files in a clear structure.

The best part is it works for anything. All you need to do is to create `.fdignore` files to mark out files you do not want to document like `LICENSE`, PNG files etc. You would see progress while running this tool, see what is going on with LLM and it is pretty fast.

I have used your tool and create this tool. The reason behind is that when processing a function or class with hundreds of lines your tool will not move, and I don't see progress behind. Later I recognized that your tool is not language agnostic nor providing fine-grained control over files to document.

**Comment by Wytamma** [comment]
Sounds like a great project @James4Ever0! I’m glad you found the write-the code useful. The file hierarchy feature seems really cool 😎 

I will create issues for the bugs that you’ve listed and hopefully can get them resolved soon. 

Do you have a way to integrate your documentation index with the current mkdocs website?

**Comment by Wytamma** [comment]
Looks like you're still adding updates to this PR so I'm going to convert it to a WIP.

**Comment by James4Ever0** [comment]
> Do you have a way to integrate your documentation index with the current mkdocs website?

I was adjusting my webpage layout. Using existing documentation framework would be nice.

**Comment by Wytamma** [comment]
Let me know if you figure out the mkdocs integration!

**Pull request closed without merging**
